### ISSUE TITLE
ionic2 fails ugliyfy-js due to ` in ortc.umd.js

### ISSUE THREAD

**Issue by demeterdev** [realtime-framework/RealtimeMessaging-Javascript#3]
integrating ortc into a new ionic2 app and was unable to build for android (works on ionic serve) due to the `` inside delegateExceptionCallback for setHeartbeat* methods starting at line 183 please update / advise I have made a local work around but this will affect others in the future.

**Comment by realtime-framework** [comment]
Hi @demeterdev, thanks for the heads-up. Can you submit a pull-request with your changes? It would be awesome.

**Comment by realtime-framework** [comment]
Hi @visdgithub, version 2.1.32 of the UMD module fixes this issue, can you please update the realtime-messaging module in NPM? Thanks.

**Comment by realtime-framework** [comment]
Version 2.1.34 solves this issue
